/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_coolreader_crengine_Engine_TaskHandler */

#ifndef _Included_org_coolreader_crengine_Engine_TaskHandler
#define _Included_org_coolreader_crengine_Engine_TaskHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
