/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_coolreader_crengine_ReaderView_SwapToCacheTask */

#ifndef _Included_org_coolreader_crengine_ReaderView_SwapToCacheTask
#define _Included_org_coolreader_crengine_ReaderView_SwapToCacheTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
