/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_coolreader_crengine_ReaderView_BitmapFactory */

#ifndef _Included_org_coolreader_crengine_ReaderView_BitmapFactory
#define _Included_org_coolreader_crengine_ReaderView_BitmapFactory
#ifdef __cplusplus
extern "C" {
#endif
#undef org_coolreader_crengine_ReaderView_BitmapFactory_MAX_FREE_LIST_SIZE
#define org_coolreader_crengine_ReaderView_BitmapFactory_MAX_FREE_LIST_SIZE 2L
#ifdef __cplusplus
}
#endif
#endif
