/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_coolreader_crengine_ReaderView_ReaderCommand */

#ifndef _Included_org_coolreader_crengine_ReaderView_ReaderCommand
#define _Included_org_coolreader_crengine_ReaderView_ReaderCommand
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
